// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-demo/app/model/internal"
)

// User is the golang structure for table user.
type User internal.User

// 注册请求
type UserApiSignUpReg struct {
	Passport 	string	`v:"required|length:6,16#账号不能为空|账号长度应当在:min到:max之间" binding:"required"` // 登录账号
	Password  	string 	`v:"required|length:6,16#请输入确认密码|密码长度应当在:min到:max之间"`
	Password2 	string 	`v:"required|length:6,16|same:Password#密码不能为空|密码长度应当在:min到:max之间|两次密码输入不相等"`
	Nickname  	string
}

//注册输入参数
type UserServiceSignUpReg struct {
	Id			int64
	Passport	string
	Password	string
	Nickname	string
}
