// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-demo/app/model/internal"
)

// UserLogin is the golang structure for table user_login.
type UserLogin internal.UserLogin

// Fill with you ideas below.

// 手机号登录请求
type AuthApiMobileLogin struct {
	Mobile string	`v:"required|phone#请输入手机号|请输入正确的手机号" binding:"required"` // 手机号
	Captcha string	`v:"required|length:6#请输入验证码|请输入正确的验证码" binding:"required"`  // 验证码
}