// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-demo/app/model/internal"
)

// UserSocial is the golang structure for table user_social.
type UserSocial internal.UserSocial

// Fill with you ideas below.