// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// UserLogin is the golang structure for table user_login.
type UserLogin struct {
    Id         int64       `orm:"id,primary"  json:"id"`         // id        
    UserName   string      `orm:"user_name"   json:"userName"`   // 登录账号  
    Password   string      `orm:"password"    json:"password"`   // 登录密码  
    UserStatus string      `orm:"user_status" json:"userStatus"` // 用户状态  
    Email      string      `orm:"email"       json:"email"`      // 邮箱      
    CreateAt   *gtime.Time `orm:"create_at"   json:"createAt"`   // 创建时间  
    UpdateAt   *gtime.Time `orm:"update_at"   json:"updateAt"`   // 更新时间  
}