// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// UserInfo is the golang structure for table user_info.
type UserInfo struct {
    Id        int64       `orm:"id,primary" json:"id"`        // id        
    NickName  string      `orm:"nick_name"  json:"nickName"`  // 昵称      
    AvatarUrl string      `orm:"avatar_url" json:"avatarUrl"` // 头像      
    Gender    string      `orm:"gender"     json:"gender"`    // 性别      
    Birthday  *gtime.Time `orm:"birthday"   json:"birthday"`  // 生日      
    Zodiac    string      `orm:"zodiac"     json:"zodiac"`    // 星座      
    Country   string      `orm:"country"    json:"country"`   // 国家      
    Province  string      `orm:"province"   json:"province"`  // 省份      
    City      string      `orm:"city"       json:"city"`      // 城市      
    Area      string      `orm:"area"       json:"area"`      // 地区      
    Profile   string      `orm:"profile"    json:"profile"`   // 个人简介  
    IdNumber  string      `orm:"id_number"  json:"idNumber"`  // 平台ID    
    Tags      string      `orm:"tags"       json:"tags"`      // 个性标签  
    CreateAt  *gtime.Time `orm:"create_at"  json:"createAt"`  // 创建时间  
    UpdateAt  *gtime.Time `orm:"update_at"  json:"updateAt"`  // 更新时间  
}