// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// UserSocial is the golang structure for table user_social.
type UserSocial struct {
    Id         int64       `orm:"id,primary"  json:"id"`         // id          
    UserId     int64       `orm:"user_id"     json:"userId"`     // 用户id      
    SocialType string      `orm:"social_type" json:"socialType"` // 账户类型    
    OpenId     string      `orm:"open_id"     json:"openId"`     // OpenId      
    UnionId    string      `orm:"union_id"    json:"unionId"`    // UnionId     
    SessionKey string      `orm:"session_key" json:"sessionKey"` // SessionKey  
    CreateAt   *gtime.Time `orm:"create_at"   json:"createAt"`   // 创建时间    
    UpdateAt   *gtime.Time `orm:"update_at"   json:"updateAt"`   // 更新时间    
}