// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-demo/app/dao/internal"
)

// userSocialDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type userSocialDao struct {
	*internal.UserSocialDao
}

var (
	// UserSocial is globally public accessible object for table user_social operations.
	UserSocial = &userSocialDao{
		internal.UserSocial,
	}
)

// Fill with you ideas below.